#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word 'bash'.

echo "PID   Process Name"

for pid in /proc/[0-9]*/status; do
    process_name=$(grep -i Name "$pid" | awk -F: '{print $2}' | tr -d '[:space:]')
    if [[ $process_name == *bash* ]]; then
        pid=$(echo "$pid" | cut -d/ -f3)
        echo "$pid    $process_name"
    fi
done
