#!/usr/bin/env bash
# This script displays specific user information from /etc/passwd.

while IFS=: read -r username _ uid _ home _
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
